# Generated by Django 3.2.25 on 2026-09-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='hospital_id_ref',
        ),
    ]
