# Generated by Django 3.2.25 on 2026-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
